// Import the PrismaClient class — the main database access object generated by Prisma
import { PrismaClient } from "@prisma/client"

// Read the database connection URL from the environment
const databaseUrl = process.env.DATABASE_URL

// Guard: if DATABASE_URL is not set, throw immediately so the app fails fast at startup
if (!databaseUrl) {
  throw new Error("DATABASE_URL environment variable is not set")
}

// Cast globalThis to allow attaching a prisma property — used to reuse the client across hot reloads
const globalForPrisma = globalThis as unknown as { prisma?: PrismaClient }

// Reuse an existing PrismaClient instance if one is already attached to globalThis,
// otherwise create a new one — this prevents exhausting the connection pool during dev hot reloads
export const prisma =
  globalForPrisma.prisma ??
  new PrismaClient({
    datasources: {
      db: {
        url: databaseUrl // Explicitly pass the database URL to the client
      }
    },
    log: ["error", "warn"] // Only log errors and warnings; omit query logs to reduce noise
  })

// If no existing client was found, store the newly created one on globalThis for future reuse
if (!globalForPrisma.prisma) {
  globalForPrisma.prisma = prisma
}
